### ISSUE TITLE
Dots and transcription box

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#100]
If you delete dots while transcription box is open, the dots appear to be deleted but the transcription window then remains. It seems that the window is hard wired to the dots, so if you write in the box and then click save, the dots reappear. It's a little counter intuitive.

**Comment by simoneduca** [comment]
Perhaps this helps
![screen shot 2015-07-15 at 16 54 50](https://cloud.githubusercontent.com/assets/8989606/8702892/4a057cba-2b12-11e5-883c-3d31aa929802.png)
