### ISSUE TITLE
Add 'hook' and opening text to front page

### ISSUE THREAD

**Issue by VVH** [zooniverse/annoTate#104]
Where the designs currently read 'Deciphering an artist's hand' and 'Dui aliquet...etc' please use:

>Uncover the lives of artists: 

>In addition to creating art, many artists wrote diaries and letters and made sketchbooks that contain rich details about their lives and creative processes. Help transcribe documents from the Tate collection and reveal the secret lives of artists.

**Comment by rogerhutchings** [comment]
Fixed via 7bccea3d129bd2666f42ace5e9bd0cd15b194ca7
