### ISSUE TITLE
After deleting an area, dragging moves the subject instead of marking an area

### ISSUE THREAD

**Issue by marten** [zooniverse/AnnoTate#115]
It feels like after deleting a marked area, the UI ends up back in both the drag/zoom state and the mark-image state.

Reproduce:

1. Mark an image
2. Click on it
3. Select "delete" from the menu
4. Try to mark another image

After step 4, you end up dragging the subject around. When you release the left mouse button, you'll notice a tiny marked area has appeared.

Video: https://www.dropbox.com/s/8ckcj1ggssh28gm/annotate%20dragging.mov?dl=0

Chrome Version 44.0.2403.125 (64-bit) on OS X 10.10

**Comment by vrooje** [comment]
I had this too.
