### ISSUE TITLE
There is a large white bar taking up space 

### ISSUE THREAD

**Issue by marten** [zooniverse/annoTate#116]
Not sure what the purpose of it is, but it seems like a footer which can be shrunk down in height. It's fixed along the bottom of the window and doesn't scale with window size, so it'll be increasingly more frustrating on smaller screens.

<img width="1275" alt="transcribe_ _annotate" src="https://cloud.githubusercontent.com/assets/277/9094318/092674fe-3ba9-11e5-8d08-47e8d87a3a48.png">

**Comment by rogerhutchings** [comment]
Thanks Marten - I've hidden it via 098d1b64b71c22776e333ec77b29bad0c3cdc9aa, but there'll probably have to be _something_ here at some point due to copyright restrictions
