### ISSUE TITLE
Transcribe dialog and annotate text context menu UI

### ISSUE THREAD

**Issue by srallen** [zooniverse/AnnoTate#117]
The text transcription interface that comes up needs to be on top if it's intended to be a modal. Also the context menu when clicking on a mark and selecting edit doesn't fully go away: 

![Annotate interface](http://i.imgur.com/gRBMOlG.png)

Using Chrome 44.0.2403.125 on OSX 10.10.4

**Comment by rogerhutchings** [comment]
Transcribe dialog now behaves the way it should, and I've taken out the copyright bar
