### ISSUE TITLE
Problem reading text

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/annoTate#120]
On toggling between the tools, the text inside the button becomes illegible. I'm not sure if it's just my screen that does it. Anyways, less contrast with the background-colour would help.

![screen shot 2015-08-06 at 09 55 27](https://cloud.githubusercontent.com/assets/8989606/9107901/a31afb7e-3c22-11e5-9196-132f4aa31491.png)

![screen shot 2015-08-06 at 09 57 01](https://cloud.githubusercontent.com/assets/8989606/9108040/895d076c-3c23-11e5-8f3f-b7abbef5cb5f.png)

Also on the About page, I struggle to read the green text.

![screen shot 2015-08-06 at 10 39 48](https://cloud.githubusercontent.com/assets/8989606/9108635/80e8a2a4-3c27-11e5-9892-a20f8b210a31.png)

**Comment by rogerhutchings** [comment]
Button legibility fixed via 2a0d94d4c3e1fb5f05cd3a01c80d8d07fa1c19e9

**Comment by rogerhutchings** [comment]
Created #121 to deal with the static page styling
