### ISSUE TITLE
image annotation delete button showing up under rotate buttons

### ISSUE THREAD

**Issue by camallen** [zooniverse/AnnoTate#122]
On my unbuntu box, firefox 39.0 only not chrome.

**Comment by CKrawczyk** [comment]
This also happens on firefox 39.0 for Max OSX.

**Comment by CKrawczyk** [comment]
This is still happening in Firefox.

![screen shot 2015-09-02 at 11 36 36 am](https://cloud.githubusercontent.com/assets/6557526/9628939/e829c67e-5166-11e5-805c-74eb9eb0b168.png)
