### ISSUE TITLE
Wrong subject set served when switching between artists

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/AnnoTate#123]
To reproduce:

1.  From the transcription page go to Home

2. Click on Find Artists and select one different from the one you were working on.

3. Click on Start Transcribing in the list of available subject sets.

4. The subject served is still from the previous artist.

(In my case I was working on Hepworth; wanted to switch to Breakwell, but still saw Hepworth subject after doing 3)

**Comment by rogerhutchings** [comment]
Yeah, I know about this one. It's saving the current subject because you haven't submitted it - the next subject would be from Breakwell. It'll be fixed by #107

**Comment by rogerhutchings** [comment]
fixed via 385cd2ed09d14bb51f961032c5f280e91e10e91c
