### ISSUE TITLE
Add Talk link

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/AnnoTate#130]
Talk currently appears to be broken - going onto https://www.zooniverse.org/#/projects/drrogg/annotate/talk just times out - so it's not in the beta. Hopefully it'll be fixed by launch.

**Comment by chrissnyder** [comment]
Seems alright now. Maybe just passing instability?

**Comment by VVH** [comment]
Once Talk is hooked up @mrniaboc is going to add a few of the Tate team in as 'researchers'. Only thing is, we don't know how this works on Panoptes. Any advice @chrissnyder or @edpaget?
