### ISSUE TITLE
Set up blog for AnnoTate

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#132]
This will get material from Tate proper and special posts for the project. Need to add Hannah Barton as contributor.

**Comment by chrissnyder** [comment]
Would there be anything that they would report in a separate blog that wouldn't also be posted at http://www.tate.org.uk/context-comment/blogs?

**Comment by rogerhutchings** [comment]
^ makes way more sense. If they set up an AnnoTate category alongside the ones they already have, we can link directly to that.

**Comment by VVH** [comment]
Tate are promising to write 12 blog posts for AnnoTate which they want on an AnnoTate blog (wordpress) and will also post two posts on the main Tate blog, which could then be repressed/blogged on the AnnoTate specific one. I think we need a blog akin to the one on Science Gossip.

**Comment by rogerhutchings** [comment]
This is a job for @mrniaboc - @VVH, can you get him a list of names / email addresses so we can set them up with WordPress accounts?

**Comment by mrniaboc** [comment]
Wordpress usernames are preferable. Is there a banner image and avatar I
can use?

**Comment by rogerhutchings** [comment]
Mailed Tate to ask for usernames, and attached images here

![large banner collage11](https://cloud.githubusercontent.com/assets/2725841/9355144/29559348-466e-11e5-842a-b212fec0c2f9.jpg)

![avatar_annotate_150715](https://cloud.githubusercontent.com/assets/2725841/9355146/3286f0ec-466e-11e5-9410-944ac1d3c6b9.jpg)

**Comment by mrniaboc** [comment]
Blog created, and currently living at annotatezoo.wordpress.com
