### ISSUE TITLE
AnnoTate header far too large and overlapping on Safari

### ISSUE THREAD

**Issue by issyl0** [zooniverse/AnnoTate#136]
I just tried to use the hosted AnnoTate as a beta tester in Safari, and found that it was quasi-impossible to zoom on the image and therefore do any transcribing comfortably because the header is so huge and overlapping. Chrome is fine.

I would try to fix it, but my command of CSS and AngularJS is very poor. :sunny: 

Screenshot:

<img width="1440" alt="screenshot 2015-08-08 12 43 48" src="https://cloud.githubusercontent.com/assets/355033/9150342/bd5bee84-3dcc-11e5-9a2d-9b46c2a0bdfb.png">

**Comment by rogerhutchings** [comment]
Thanks @issyl0 - I suspect Safari's got some beef with how it renders SVGs

**Comment by issyl0** [comment]
:+1: (And thanks for having built it!)

**Comment by issyl0** [comment]
The "New Zooniverse Project Betas" email I got linked to http://preview.zooniverse.org/annotate, but this repo links to http://preview.zooniverse.org/transcribe. Which one should I be using, or are they the same but run in parallel?

**Comment by rogerhutchings** [comment]
Cool :) Out of interest, where did you see the `/transcribe` link?

**Comment by issyl0** [comment]
In the README.

**Comment by rogerhutchings** [comment]
Applying `width: 100%` seems to fix it - Safari appears to have some sort of issue with SVGs not taking their container's size.
