### ISSUE TITLE
For artists search page_just present artists' names and no images

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#140]

**Comment by rogerhutchings** [comment]
...why?

**Comment by simoneduca** [comment]
I think the idea is that the current images look quite odd with different heights. Since we can't modify them, getting rid of them might look better.

**Comment by chrissnyder** [comment]
You can force the bounding boxes to be equal heights, and have the images
adjust automatically if that's a big worry.

**Comment by rogerhutchings** [comment]
Plus it uses masonry, so they'll all fit together like a wall. It'll be fine

**Comment by VVH** [comment]
Some of the images are landscape and some are portrait, I think it looks a bit odd. Plus, some of the photos aren't very compelling, e.g. Breakwell.

**Comment by rogerhutchings** [comment]
That's too subjective a reason to trash a bunch of work I've already done, and significantly change a design the Tate's already signed off on. I'm sure they have some more compelling photos we can use.
