### ISSUE TITLE
All working!

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#153]
The following browser and operating systems have been tested and are reportedly running ok:

Firefox (40.0.2) on mac OS X 10.10.5 
Safari (Version 8.0.5 (10600.5.17) on Mac OS X 10.10.3 and 10.10.5
Chrome (Version 8.0.5 (10600.5.17) on n Mac OS X 10.10.3
Chrome 44.0.2403.157 (CJL's computer, not sure of OS version, but Mac)

**Comment by rogerhutchings** [comment]
Cool, will hit Windows later / tomorrow, thanks
