### ISSUE TITLE
New, final tutorial content

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#158]
Sorry about this. Another copyright related issue has come up which meant I had to redo the gifs. Have taken the opportunity to rewrite the text as well. https://docs.google.com/document/d/1K9Uo7xCQmDoxrqpkZGKt__aFlOrTVRNRTaYOtGcPRZs/edit#

![step1_final](https://cloud.githubusercontent.com/assets/6482891/9499534/ea632506-4c17-11e5-8688-0fa618cfefd2.gif)
![step2_final_nextimagegif](https://cloud.githubusercontent.com/assets/6482891/9499536/ea646a10-4c17-11e5-8605-9c4d1c42239f.gif)
![step3_final_place dots](https://cloud.githubusercontent.com/assets/6482891/9499535/ea639cb6-4c17-11e5-9a0f-9475eed4252d.gif)
![step5_final_delete dots](https://cloud.githubusercontent.com/assets/6482891/9499538/ea684c70-4c17-11e5-9eeb-95992db652b7.gif)
![step6_rotatefinal](https://cloud.githubusercontent.com/assets/6482891/9499537/ea651866-4c17-11e5-9753-efd322dfbc4a.gif)
![step7_final_deletioninsertion](https://cloud.githubusercontent.com/assets/6482891/9499539/ea6c7ed0-4c17-11e5-984f-d9286813dfad.gif)
![step9_final_marginalia](https://cloud.githubusercontent.com/assets/6482891/9499540/ea7861aa-4c17-11e5-8682-9a08a18e606d.gif)
![step10_final_annotateimage](https://cloud.githubusercontent.com/assets/6482891/9499541/ea7a2bc0-4c17-11e5-8d1c-ebed379c8e6c.gif)

**Comment by rogerhutchings** [comment]
Closed via #157
