### ISSUE TITLE
Urgent: Missing artists and some material under the wrong person

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#163]
Sian says that these artists are missing: 

Felicia Browne
Duncan Grant
Ian Hamilton-Finlay
Nigel Henderson
John Piper

Henry Scott Tuke is also not in the artists list but we see that his works are listed under Thomas Cooper Gotch.  These items should feature under a separate Henry Scott Tuke option in the main artists list.

**Comment by rogerhutchings** [comment]
The missing artists were never provided as part of the Tate upload. Henry Scott Tuke's sets had the wrong `artistId` set on them in their metadata, which I've fixed (ref 76c025e11f45702da07352357a200330f734a34f)
