### ISSUE TITLE
link from talk page to classify is broken

### ISSUE THREAD

**Issue by camallen** [zooniverse/AnnoTate#179]
classify link resolves to https://anno.tate.org.uk//#/classify

<img width="880" alt="screen shot 2015-09-06 at 14 13 00" src="https://cloud.githubusercontent.com/assets/295329/9704504/78ccbe1a-54a1-11e5-89c1-c686ace75aa6.png">

**Comment by VVH** [comment]
Hey @camallen, not sure if you or someone else fixed this, but it's working for me in Chrome this morning. @rogerhutchings did you make a change?

**Comment by rogerhutchings** [comment]
I did - I assumed it was set by the `redirect` property on the project and removed the trailing slash on it.

**Comment by camallen** [comment]
still not working for me...try the *classify* link on this page, https://www.zooniverse.org/projects/drrogg/annotate/talk

**Comment by rogerhutchings** [comment]
So it's not set by that - where does it get created then?

**Comment by camallen** [comment]
not sure - it'll be related to the work to remove the hash char in url's though, just something that got overlooked i reckon.

**Comment by camallen** [comment]
[here] i think(https://github.com/zooniverse/Panoptes-Front-End/blob/5f8ae4fbcb5451874b2b30d6843fdedb946e1eb8/app/pages/project/index.cjsx#L97) - i'll see if i can't get a PR to fix this.

**Comment by VVH** [comment]
I think that @edpaget was working on the redirect stuff last week so am looping him in.

**Comment by camallen** [comment]
should be fixed by the PR on PFE.
