### ISSUE TITLE
Login error - avatar not found

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/AnnoTate#192]
Possibly related to #188 
On Chrome, I get this when I try to log in

![screen shot 2015-09-17 at 10 10 41](https://cloud.githubusercontent.com/assets/8989606/9929471/bbba6a34-5d24-11e5-88c8-650c1dcb0941.png)

![screen shot 2015-09-17 at 10 16 03](https://cloud.githubusercontent.com/assets/8989606/9929542/3c649aba-5d25-11e5-8e13-881eb960acec.png)

On inspection, it seems I am logged in, because if I submit a transcription the auth token is there.

However users will think they can't log in and give up. 
Also, 'enter' button should be enabled for login submission.

**Comment by rogerhutchings** [comment]
I'm trashing login today anyway to use the OAuth flow instead, but thanks for logging this
