### ISSUE TITLE
IE 11 doesn't support promises

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/AnnoTate#194]
I think @rogerhutchings is aware of this, just logging for the record.

![image](https://cloud.githubusercontent.com/assets/8989606/9933311/1aed5e40-5d42-11e5-89c3-f332a633e640.png)

Thread with possible solution:
https://github.com/github/fetch/issues/114

**Comment by rogerhutchings** [comment]
Fixed via ccb6625708df8a682c25755318034fdb3615d712

This adds the `es6-promise` polyfill to for `panoptes-javascript-client`

**Comment by simoneduca** [comment]
This is what I get now

![ietate](https://cloud.githubusercontent.com/assets/8989606/9934595/3fa4cfd6-5d4a-11e5-94ca-f4d62caa686e.png)
and the console
![ietate2](https://cloud.githubusercontent.com/assets/8989606/9934609/51103422-5d4a-11e5-89df-a202f4b3499b.png)

**Comment by simoneduca** [comment]
Fixed via #213
