### ISSUE TITLE
sign out of oauth session on the api server

### ISSUE THREAD

**Issue by camallen** [zooniverse/AnnoTate#197]
see https://github.com/zooniverse/wildcam-gorongosa/issues/184, basically the session is always valid. pressing sign out should sign you out of the panoptes session as well. 

this fixes it for wildcam, a similar post on signout should fix it for annotate
https://github.com/zooniverse/wildcam-gorongosa/pull/189/files

**Comment by rogerhutchings** [comment]
fixed via fede65c72ea454ac8170843a5ccd7abd0b5cfb98
