### ISSUE TITLE
Getting rid of unwanted markings

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/annoTate#47]
If you click on the discard button in the transcription window with nothing transcribed, the corresponding markings should disappear. You can get this behaviour by clicking on the "x" but people will definitely expect "discard" to work in the same way.

**Comment by rogerhutchings** [comment]
So there are two behaviours needed - one is to delete the points, the other is to close the window, and both aren't quite right as they are. Discard is actually supposed to mean discard changes, but you're right, it's not obvious. I've asked to get a designer in to work on these interactions.

**Comment by rogerhutchings** [comment]
Related to #63

**Comment by rogerhutchings** [comment]
I ended up creating a context menu, so you can choose to edit or delete from there.
