### ISSUE TITLE
Always minify JS when deploying

### ISSUE THREAD

**Issue by perry** [zooniverse/annoTate#50]
There's currently an aptly named environment variable, `ENVIRONMENT`, that needs to be set to `'production'` for JS minification to occur. 

Having the env variable seems a bit overkill and easy to miss (I just did), it would be much better to explicitly call the `uglify()` task in the build steps.

**Comment by rogerhutchings** [comment]
#7

**Comment by rogerhutchings** [comment]
Fixed, `gulp production` minifies all the things
