### ISSUE TITLE
Check with Cam about how to get aggregated data out

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/AnnoTate#59]
In order to show what's been done and what hasn't

**Comment by rogerhutchings** [comment]
There's some backend work to be done on this, but Cam's on it

**Comment by rogerhutchings** [comment]
@camallen is there still work to do for this?

**Comment by camallen** [comment]
yeah - we need to make the aggregations for certain workflows public scope if flagged on the workflow.
