### ISSUE TITLE
Make transcription box respond to points on page.

### ISSUE THREAD

**Issue by VVH** [zooniverse/annoTate#61]
From the alpha feedback form: 'Very clear, uncluttered, and easy to use. But it is a bit annoying that the pop-up transcription box always appears in the middle of the screen - could it not respond to the position of the dots just placed (so that it doesn't cover them up!)'

**Comment by rogerhutchings** [comment]
Added via https://github.com/zooniverse/annoTate/commit/d090456d1d7ab1c942f5715216d53fa624433360#diff-6037a9c70e64b22c46b3877dd931b783R117
