### ISSUE TITLE
Allow deletion and movement of the dots

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#63]

**Comment by rogerhutchings** [comment]
You can drag temp dots around - I'll extend that. How do you see dot deletion working?

**Comment by rogerhutchings** [comment]
New UI now produces a context menu, allowing you to delete or edit annotations

**Comment by rogerhutchings** [comment]
Draggable dots were playing up a bit, so they've temporarily been removed. The `draggable` directive I wrote probably needs a bit of love

**Comment by rogerhutchings** [comment]
Superseded by #191
