### ISSUE TITLE
fix the cursor and box movement. 

### ISSUE THREAD

**Issue by VVH** [zooniverse/annoTate#64]
From the alpha: "Zooming in and out on the documents was easy. Scrolling up and down was a little clunky as if the annotate tool was selected and you were scrolling up to see the next line it assumed you were starting another annotation - so you have to pretend you were and deleted the blank annotation.
Also I left the browse to do some other work on the computer an when I returned the annotate text window did not work properly. I could mark the 2 sides of the text line, the window popped up over the top of the line, when I tried to move it, the site would not let me put the box down.  The mouse cursor was above it and the window just followed the mouse around the screen. It the text box was active I could still type and use TAB to go to the buttons."

**Comment by rogerhutchings** [comment]
Fixed the first issue, latter is an edge case and has probably been fixed - can't verify for sure without seeing what the user actually did
