### ISSUE TITLE
Make this work on an Ipad? Maybe?

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#65]

**Comment by rogerhutchings** [comment]
I'm up for it - I think Heath's full page design would work better too for this. Are there any specific reasons it won't?

**Comment by rogerhutchings** [comment]
I've used Hammer to add support for tap / drag events in the rebuild, and the new UI should be kinder for touch interface users. We'll need a test device at some point though.

**Comment by rogerhutchings** [comment]
Superseded by #190
