### ISSUE TITLE
"next document" button does not work in firefox

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/annoTate#67]
When hitting "ok" on the next document modal firefox gives the following error:

![screen shot 2015-04-23 at 2 27 57 pm](https://cloud.githubusercontent.com/assets/6557526/7298104/3faf012a-e9c5-11e4-9151-1a7b778a538c.png)

**Comment by CKrawczyk** [comment]
Update: Clearing my cache and local storage made the next button work.

**Comment by rogerhutchings** [comment]
This should also have been fixed by https://github.com/zooniverse/transcribe/pull/76

**Comment by rogerhutchings** [comment]
Confirmed fixed, although I haven't deployed a new version yet (and probably won't to the alpha url)
