### ISSUE TITLE
Next document keyboard shortcut

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#69]
Increase accessiblity: More key commands, less mouse dependant

**Comment by rogerhutchings** [comment]
Specifically, have a keyboard shortcut for Next Document, and ensure users can arrow between the modal options. 

Guessing next text will be hard if not impossible - the user that logged the issue has RSI, and his problem was switching between mouse and keyboard. Unfortunately, we need people to tell us where the text lines are, so they can't really be guessed.

**Comment by rogerhutchings** [comment]
There are more keyboard shortcuts now, and I'll add an issue to document them; closing
