### ISSUE TITLE
new subjects not appearing

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/annoTate#77]
Lisa's been doing some transcribing for me and is getting the "out of data to transcribe" message but I know she definitely hasn't done all of them. I don't think I've actually seen any transcriptions on the new stuff - I would have expected at least one or two. Sorry, I realise this is a pretty vague bug.

**Comment by rogerhutchings** [comment]
I rebuilt the subject set in b682195ae65c7fa2ae08b39579b308111f45f0ef, and it appears to be okay - we can reopen if needs be
