### ISSUE TITLE
multiple transcriptions per line

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/AnnoTate#79]
In the tutorial we tell people that if a single line has been written by two or more people to give multiple transcriptions. Not everyone is going to follow this instruction and there are going to be times when people accidentally give multiple transcriptions for a line that should only has one. Separating these two cases is going to be really hard, if not impossible, so we should think about whether it is worth asking users to do this.

**Comment by ggdhines** [comment]
Cam just said we should just allow for some tag in the next to denote multiple writers. MUCH easier

**Comment by rogerhutchings** [comment]
I'm going to close this, unless @ggdhines you have any suggestions for edits to the tutorial / guide (https://anno.tate.org.uk/#/guide/overview)
