### ISSUE TITLE
multiple lines per transcription

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/AnnoTate#80]
As opposed to my previous issue. Some users are entering multiple lines per one transcription - in some cases, the whole text at once. We should have an error pop up if there is a new line character in the transcription.

**Comment by ggdhines** [comment]
should add that we can split transcriptions based on newline characters but it will make comparing against gold standard more difficult

**Comment by rogerhutchings** [comment]
ref #79

**Comment by rogerhutchings** [comment]
Enter now saves and closes, basically preventing this

**Comment by ggdhines** [comment]
As a side note - there are some idiots who transcribe multiple lines at once without using the newline character. So I think we will always need to be cautious about this.
