### ISSUE TITLE
dealing with foreign text

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/AnnoTate#81]
so users are told to ignore foreign text (or at least put markup around it). Some users are ignoring that and so we have some transcriptions with both English and French in it. (for example) not the end of the world but is it so bad to have French in the transcriptions? (or another language)  If not, we should remove this from the instructions. Otherwise, we could insert a set where we do a quick lookup and see if there are any words in the transcriptions where are French, German etc. but not English - in which case we tell the user

**Comment by rogerhutchings** [comment]
@VVH ^

**Comment by VVH** [comment]
@rogerhutchings @ggdhines I think we need to ask people to transcribe everything but just use the 'foreign text' or 'not English' buttons around the relevant words.

**Comment by ggdhines** [comment]
the problem is that people don't always follow the instructions - I can point you to several examples from the alpha test where people just started writing in French

**Comment by rogerhutchings** [comment]
I'm going to close this, unless @ggdhines you have any suggestions for edits to the tutorial / guide (https://anno.tate.org.uk/#/guide/overview)

**Comment by ggdhines** [comment]
Issue zooniverse/aggregation#16 will handle this.
