### ISSUE TITLE
how to deal with multiple columns

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/AnnoTate#82]
![transcription](https://cloud.githubusercontent.com/assets/6626461/7347270/e7e13950-ecde-11e4-88ab-d46a207a8146.jpeg)

So there are two columns here - but not everyone is going to notice this. The text on the right hand side is completely separate from the left hand side. BTW this is from the Bentham collection - but seems possible that something similar could happen with Tate.  So partly this is an aggregation issue but also an issue about how users are going to use the text. If they are just searching for individual words - fine. But if they are searching for phrases or reading the text, such cases are going to matter.

**Comment by rogerhutchings** [comment]
@VVH ^

**Comment by rogerhutchings** [comment]
I think that'll be a tutorial content thing

**Comment by rogerhutchings** [comment]
I'm going to close this, unless @VVH @ggdhines you have any suggestions for edits to the tutorial / guide (https://anno.tate.org.uk/#/guide/overview)
